kafka:
  endpoint: "localhost"
topics:
  - name: voxceleb_test_files
operators:
  list_files:
    factory: deep_speaker.feature.list_files:list_files
    sinks:
      - voxceleb_test_files
config:
  dataset:
    voxceleb2_path: "/home/bipbip/dataset/voxceleb2/test"
