kafka:
  endpoint: "localhost"
topics:
  - name: voxceleb_test_files
  - name: feature_utterance
    encoder: makinage.encoding.pickle
    partition_selector: deep_speaker:feature_utterance_partition_selector
operators:
  compute_mfcc:
    factory: deep_speaker.feature.compute_features:compute_features
    sources:
      - voxceleb_test_files
    sinks:
      - feature_utterance
config:
  train:
    summary_path: /tmp/deep-speaker
    batch_size: 64
    learning_rate: 0.01
    epoch_count: 10
    model: deep_speaker.model.cnn1:create_model
    loss: torch.nn:CrossEntropyLoss
    optimizer: torch.optim:Adam

